package com.folderspan.service.session

import android.os.Process
import androidx.test.platform.app.InstrumentationRegistry
import com.folderspan.AndroidContextHolder
import com.folderspan.service.http.server.HttpPortSchemeSwitchingProxy
import com.folderspan.service.http.tls.DeviceTlsIdentity
import com.folderspan.utils.FileAccessPermission
import com.folderspan.utils.FileUtils
import java.io.DataInputStream
import java.io.File
import javax.net.ssl.SSLServerSocket
import javax.net.ssl.SSLSocket
import kotlin.test.Test
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.junit.Assume.assumeTrue

/**
 * Opt-in real Wi-Fi benchmark; sends generated bytes, never user files.
 * Build with -PdeviceTestApplicationId=com.folderspan.core.transferbenchmark, then run
 * am instrument -w -e class com.folderspan.service.session.DeviceSessionThroughputAndroidTest
 * -e sessionBenchmark true com.folderspan.core.transferbenchmark/androidx.test.runner.AndroidJUnitRunner.
 * Pass the printed fingerprint and phone IP to DeviceSessionThroughputJvmTest.
 * Add -e fileSource true to read a generated temporary file through FileUtils.
 * -e readBlockSizes 262144,65536,65536,262144 compares read sizes in alternating order.
 * Keep the test package awake on devices that freeze background instrumentation.
 */
class DeviceSessionThroughputAndroidTest {
    @Test
    fun serveGeneratedData() = runBlocking(Dispatchers.IO) {
        val arguments = InstrumentationRegistry.getArguments()
        assumeTrue(arguments.getString("sessionBenchmark") == "true")
        AndroidContextHolder.initialize(InstrumentationRegistry.getInstrumentation().targetContext)
        val port = arguments.getString("port", "15240").toInt()
        val count = arguments.getString("connections", "4").toInt()
        val fileSource = arguments.getString("fileSource") == "true"
        val readBlockSizes = arguments.getString("readBlockSizes", "262144").split(',').map(String::toInt)
        require(readBlockSizes.all { it in 1..1024 * 1024 })
        val sourceFile = if (fileSource) File.createTempFile(
            "session-throughput-", ".bin", InstrumentationRegistry.getInstrumentation().targetContext.cacheDir,
        ) else null
        val proxy = HttpPortSchemeSwitchingProxy()
        val server = DeviceTlsIdentity.createSessionServerSslContext()
            .serverSocketFactory.createServerSocket(port) as SSLServerSocket
        server.soTimeout = 90_000
        server.advertiseDeviceSessionAlpn()
        val block = ByteArray(256 * 1024) { it.toByte() }
        try {
            proxy.start(port + 1, port, port, bindLan = true, allowPlainHttpOnLan = false)
            println("SESSION_BENCHMARK_READY port=$port plan=${DeviceSessionWindowPlan.fromMemory()}")
            println("SESSION_BENCHMARK_FINGERPRINT ${DeviceTlsIdentity.loadOrCreate().fingerprintSha256}")
            repeat(count) { connectionIndex ->
                (server.accept() as SSLSocket).use { socket ->
                    socket.soTimeout = 30_000
                    socket.advertiseDeviceSessionAlpn()
                    socket.startHandshake()
                    check(socket.hasDeviceSessionAlpn())
                    val input = DataInputStream(socket.inputStream)
                    val mode = input.readInt()
                    val window = input.readInt()
                    val blocks = if (mode == 2) input.readInt() else 512
                    check(blocks in 1..8192)
                    check(window == 0 || window in 256 * 1024..4 * 1024 * 1024)
                    val readBlockSize = readBlockSizes[connectionIndex % readBlockSizes.size]
                    val totalBytes = blocks * block.size.toLong()
                    if (sourceFile != null && sourceFile.length() != totalBytes) {
                        sourceFile.outputStream().buffered(block.size).use { output ->
                            repeat(blocks) { output.write(block) }
                        }
                    }
                    val started = System.nanoTime()
                    val cpuStarted = Process.getElapsedCpuTime()
                    if (mode == 0) {
                        repeat(512) { socket.outputStream.write(block) }
                        socket.outputStream.flush()
                        check(input.read() == 1)
                    } else {
                        coroutineScope {
                            val plan = if (window == 0) DeviceSessionWindowPlan.fromMemory()
                            else DeviceSessionWindowPlan(16 * 1024 * 1024, window, 4)
                            val transport = DeviceSessionTransport(
                                AndroidDeviceSessionByteChannel(socket), plan, isClient = false,
                            )
                            val job = transport.start(this)
                            try {
                                withTimeout(90_000) {
                                    val stream = if (mode == 2) {
                                        val open = transport.connection.incomingEvents.receive()
                                        check(open.type == DeviceSessionFrameType.Open)
                                        open.streamId
                                    } else transport.connection.openStream()
                                    if (sourceFile == null) {
                                        repeat(blocks) { transport.connection.sendData(stream, block) }
                                    } else {
                                        FileUtils.readFileRangeChunks(
                                            FileAccessPermission.Allowed, sourceFile.path, 0, totalBytes,
                                            readBlockSize.toLong(),
                                        ).collect { chunk ->
                                            transport.connection.sendData(stream, chunk.getOrThrow().second)
                                        }
                                    }
                                    transport.connection.sendTrailer(stream)
                                    if (mode == 2) transport.connection.incomingEvents.receiveCatching()
                                    else transport.connection.ping(byteArrayOf(1))
                                }
                            } finally {
                                transport.close()
                                job.cancelAndJoin()
                            }
                        }
                    }
                    println("SESSION_BENCHMARK_RESULT mode=$mode window=$window elapsedMs=${(System.nanoTime() - started) / 1_000_000} cpuMs=${Process.getElapsedCpuTime() - cpuStarted} fileSource=$fileSource readBlockBytes=$readBlockSize")
                }
            }
        } finally {
            server.close()
            proxy.stop()
            sourceFile?.delete()
        }
    }
}
