package com.folderspan.pro.presentation.screen.marketplace

import strings.AppStrings

enum class MarketplaceVisualTone {
    Primary,
    Secondary,
    Tertiary,
}

data class HeroBanner(
    val badge: String,
    val tag: String,
    val title: String,
    val subtitle: String,
    val reason: String,
    val iconText: String,
    val tone: MarketplaceVisualTone,
)

data class MarketplaceStaticCardUi(
    val title: String,
    val category: String,
    val summary: String,
    val rating: String,
    val ratingCount: String,
    val downloads: String,
    val version: String,
    val pluginId: String,
    val authorId: String,
    val status: String,
    val statusTone: MarketplaceVisualTone,
    val iconText: String,
    val iconTone: MarketplaceVisualTone,
)

fun marketplaceHeroBanners() = listOf(
    HeroBanner(
        badge = AppStrings.ui_today_s_recommendation,
        tag = AppStrings.ui_editor_s_picks,
        title = "Flow Render Pro",
        subtitle = AppStrings.ui_great_helper_teams_automate_tasks,
        reason = AppStrings.ui_repeated_work_can_organized_into_fixed_process_team_use,
        iconText = "FR",
        tone = MarketplaceVisualTone.Primary,
    ),
    HeroBanner(
        badge = AppStrings.ui_everyone_using_it,
        tag = AppStrings.ui_popular_recommendations,
        title = "DataSync Hub",
        subtitle = AppStrings.ui_keep_data_consistent_across_multiple_locations,
        reason = AppStrings.ui_help_you_keep_data_different_places_synchronized_reduce_trouble,
        iconText = "DS",
        tone = MarketplaceVisualTone.Secondary,
    ),
    HeroBanner(
        badge = AppStrings.ui_new_arrival,
        tag = AppStrings.ui_new_products_shelves,
        title = "SmartMail AI",
        subtitle = AppStrings.ui_process_email_faster,
        reason = AppStrings.ui_it_helps_you_draft_reply_based_content_email_can,
        iconText = "SM",
        tone = MarketplaceVisualTone.Tertiary,
    ),
)

fun marketplaceFeaturedCards() = listOf(
    MarketplaceStaticCardUi(
        title = "Flow Render Pro",
        category = AppStrings.ui_flow_labs_automation,
        summary = AppStrings.ui_organize_repetitive_tasks_into_clear_processes_reuse_commonly_used,
        rating = "4.9",
        ratingCount = AppStrings.ui_128_ratings,
        downloads = AppStrings.ui_12_4k_downloads,
        version = "v2.8.1",
        pluginId = "flow-render-pro",
        authorId = "flow-labs",
        status = AppStrings.ui_passed_inspection,
        statusTone = MarketplaceVisualTone.Primary,
        iconText = "FR",
        iconTone = MarketplaceVisualTone.Primary,
    ),
    MarketplaceStaticCardUi(
        title = "DataSync Hub",
        category = AppStrings.ui_datacore_data_synchronization,
        summary = AppStrings.ui_keep_multiple_data_consistent_reduce_repeated_entry_manual_verification,
        rating = "4.8",
        ratingCount = AppStrings.ui_96_ratings,
        downloads = AppStrings.ui_9_8k_downloads,
        version = "v1.9.4",
        pluginId = "data-sync-hub",
        authorId = "datacore-labs",
        status = AppStrings.ui_pay,
        statusTone = MarketplaceVisualTone.Secondary,
        iconText = "DS",
        iconTone = MarketplaceVisualTone.Secondary,
    ),
    MarketplaceStaticCardUi(
        title = "Ops Insight Lite",
        category = AppStrings.ui_ops_team_run_reminders,
        summary = AppStrings.ui_centrally_view_errors_slowdowns_online_changes_facilitate_daily_inspections,
        rating = "4.7",
        ratingCount = AppStrings.ui_61_ratings,
        downloads = AppStrings.ui_6_3k_downloads,
        version = "v1.4.2",
        pluginId = "ops-insight-lite",
        authorId = "ops-team-17",
        status = AppStrings.ui_latest_updates,
        statusTone = MarketplaceVisualTone.Tertiary,
        iconText = "OI",
        iconTone = MarketplaceVisualTone.Tertiary,
    ),
)

fun marketplaceNewCards() = listOf(
    MarketplaceStaticCardUi(
        title = "SmartMail AI",
        category = AppStrings.ui_inboxworks_intelligent_assistant,
        summary = AppStrings.ui_it_helps_you_draft_reply_based_content_email_can,
        rating = "4.8",
        ratingCount = AppStrings.ui_54_ratings,
        downloads = AppStrings.ui_4_1k_downloads,
        version = "v1.0.0",
        pluginId = "smartmail-ai",
        authorId = "inboxworks",
        status = AppStrings.ui_new_product,
        statusTone = MarketplaceVisualTone.Tertiary,
        iconText = "SM",
        iconTone = MarketplaceVisualTone.Tertiary,
    ),
    MarketplaceStaticCardUi(
        title = "Mail Focus",
        category = AppStrings.ui_inboxworks_mail,
        summary = AppStrings.ui_automatically_organize_emails_remind_important_messages_keep_your_inbox,
        rating = "4.7",
        ratingCount = AppStrings.ui_31_ratings,
        downloads = AppStrings.ui_2_2k_downloads,
        version = "v0.9.8",
        pluginId = "mail-focus",
        authorId = "inboxworks-labs",
        status = AppStrings.ui_new_product_launch,
        statusTone = MarketplaceVisualTone.Tertiary,
        iconText = "MF",
        iconTone = MarketplaceVisualTone.Tertiary,
    ),
)

fun marketplaceTrendCards() = listOf(
    MarketplaceStaticCardUi(
        title = "Ops Insight Lite",
        category = AppStrings.ui_ops_team_run_reminders,
        summary = AppStrings.ui_centrally_view_errors_slowdowns_online_changes_facilitate_daily_inspections,
        rating = "4.7",
        ratingCount = AppStrings.ui_61_ratings,
        downloads = AppStrings.ui_6_3k_downloads,
        version = "v1.4.2",
        pluginId = "ops-insight-lite",
        authorId = "ops-team-17",
        status = AppStrings.ui_pay,
        statusTone = MarketplaceVisualTone.Secondary,
        iconText = "OI",
        iconTone = MarketplaceVisualTone.Tertiary,
    ),
    MarketplaceStaticCardUi(
        title = "Flow Render Pro",
        category = AppStrings.ui_flow_labs_automation,
        summary = AppStrings.ui_organize_repetitive_tasks_into_clear_processes_reuse_commonly_used,
        rating = "4.9",
        ratingCount = AppStrings.ui_128_ratings,
        downloads = AppStrings.ui_12_4k_downloads,
        version = "v2.8.1",
        pluginId = "flow-render-pro",
        authorId = "flow-labs",
        status = AppStrings.ui_passed_inspection,
        statusTone = MarketplaceVisualTone.Primary,
        iconText = "FR",
        iconTone = MarketplaceVisualTone.Primary,
    ),
)

fun marketplaceFreeCards() = listOf(
    MarketplaceStaticCardUi(
        title = "Secure Form Kit",
        category = AppStrings.ui_formify_studio_form,
        summary = AppStrings.ui_form_automatically_checks_content_retains_draft_which_suitable_collaborative,
        rating = "4.8",
        ratingCount = AppStrings.ui_72_ratings,
        downloads = AppStrings.ui_8_2k_downloads,
        version = AppStrings.ui_stable_version_1_6_0,
        pluginId = "secure-form-kit",
        authorId = "formify-studio",
        status = AppStrings.ui_free,
        statusTone = MarketplaceVisualTone.Primary,
        iconText = "SF",
        iconTone = MarketplaceVisualTone.Secondary,
    ),
    MarketplaceStaticCardUi(
        title = "Flow Render Pro",
        category = AppStrings.ui_flow_labs_automation,
        summary = AppStrings.ui_organize_repetitive_tasks_into_clear_processes_reuse_commonly_used,
        rating = "4.9",
        ratingCount = AppStrings.ui_128_ratings,
        downloads = AppStrings.ui_12_4k_downloads,
        version = "v2.8.1",
        pluginId = "flow-render-pro",
        authorId = "flow-labs",
        status = AppStrings.ui_passed_inspection,
        statusTone = MarketplaceVisualTone.Primary,
        iconText = "FR",
        iconTone = MarketplaceVisualTone.Primary,
    ),
)
